# Generated by Django 2.1 on 2018-12-22 13:37

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('country', models.CharField(choices=[('IN', 'India')], max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('venue_name', models.CharField(max_length=50)),
                ('venue_address', models.TextField()),
                ('guest_invites', models.PositiveSmallIntegerField()),
                ('seats_booked', models.PositiveSmallIntegerField()),
                ('appeared', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventFee',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('performer_fee', models.PositiveIntegerField()),
                ('audience_fee', models.PositiveIntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventFreebieMap',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('distribution_count', models.PositiveSmallIntegerField()),
                ('total_cost', models.FloatField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventPersonMap',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('person_type', models.CharField(choices=[('PAID_PERFORMER', 'Paid Performer'), ('GUEST_PERFORMER', 'Guest Performer'), ('GUEST_SPEAKER', 'Guest Speaker'), ('VOLUNTEER', 'Volunteer'), ('ORGANIZER', 'Organizer'), ('AUDIENCE', 'Audience')], max_length=20)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventSponsorMap',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sponsor_type', models.CharField(choices=[('MEDIA', 'Media'), ('FINANCIAL', 'Financial'), ('IN KIND', 'In Kind')], max_length=2)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('venue', models.FloatField()),
                ('food_inlcusive', models.BooleanField()),
                ('food', models.FloatField(blank=True, null=True)),
                ('sound', models.FloatField(blank=True, null=True)),
                ('camera', models.FloatField(blank=True, null=True)),
                ('media', models.FloatField(blank=True, null=True)),
                ('freebies', models.FloatField(blank=True, null=True)),
                ('travel', models.FloatField(blank=True, null=True)),
                ('others', models.FloatField(blank=True, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Freebie',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('KEYCHAIN', 'Key Chain'), ('STICKER', 'Strickers'), ('SOUVENIR', 'Souvenir'), ('T-SHIRTS', 'T-SHIRTS')], max_length=20)),
                ('vendor_name', models.CharField(max_length=50)),
                ('vendor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vendor_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('pincode', models.IntegerField()),
                ('total_units', models.PositiveSmallIntegerField()),
                ('unit_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('MUSIC', 'Music'), ('SPORTS', 'Sports')], max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PerformerDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('occupation_type', models.CharField(choices=[('ST', 'Student'), ('CO', 'Corporate'), ('SE', 'Self-Employed'), ('UE', 'Unemployed')], max_length=2)),
                ('education', models.TextField(help_text='Enter your latest degree.')),
                ('photograph', models.ImageField(upload_to=events.models.user_directory_path)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('youtube_channel', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('interest_area', models.ForeignKey(help_text='Please enter upto 5 aspirational interests.', on_delete=django.db.models.deletion.CASCADE, to='events.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('DNM', 'Other')], max_length=3)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Only 10-digit mobile number.', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interest_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelCost',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cab_cost', models.FloatField()),
                ('flight_cost', models.FloatField(blank=True, null=True)),
                ('total_cost', models.FloatField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Person')),
            ],
        ),
        migrations.AddField(
            model_name='performerdetail',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Person'),
        ),
        migrations.AddField(
            model_name='eventsponsormap',
            name='sponsor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Sponsor'),
        ),
        migrations.AddField(
            model_name='eventpersonmap',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Person'),
        ),
        migrations.AddField(
            model_name='eventfreebiemap',
            name='freebie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Freebie'),
        ),
    ]
