# Generated by Django 2.1 on 2018-12-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelcost',
            old_name='cab_cost',
            new_name='cab',
        ),
        migrations.RenameField(
            model_name='travelcost',
            old_name='flight_cost',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='travelcost',
            old_name='total_cost',
            new_name='total',
        ),
    ]
