# Generated by Django 2.1 on 2018-12-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181222_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='explain_others',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelcost',
            name='explain_others',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travelcost',
            name='other',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
