# Generated by Django 2.1 on 2018-12-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181222_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
