# Generated by Django 2.1 on 2018-12-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20181222_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubelink',
            name='title',
            field=models.CharField(default='old', max_length=50),
            preserve_default=False,
        ),
    ]
