# Generated by Django 2.1 on 2018-12-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_youtubelink_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubelink',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
