# Generated by Django 2.1 on 2018-12-23 05:23

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20181222_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='address',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(default='1', upload_to=events.models.sponsor_directory_path),
            preserve_default=False,
        ),
    ]
