# Generated by Django 2.1 on 2018-12-25 11:39

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20181223_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.ImageField(default='#', upload_to=events.models.event_icon_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='one_liner',
            field=models.CharField(default='1', max_length=500),
            preserve_default=False,
        ),
    ]
