# Generated by Django 2.1 on 2018-12-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20181225_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performerdetail',
            name='event_id',
        ),
    ]
