# Generated by Django 2.1 on 2018-12-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20181226_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='one_liner',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
